//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.28 at 11:05:57 PM PDT 
//


package com.cmpe276.dbase;

//import java.sql.Timestamp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StandardCost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ListPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Size">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ProductCategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ProductModelID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SellStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="SellEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DiscontinuedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ThumbNailPhoto" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="ThumbnailPhotoFileName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{}ProductModel"/>
 *         &lt;element ref="{}ProductCategory"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ProductID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductType", propOrder = {
    "name",
    "productNumber",
    "color",
    "standardCost",
    "listPrice",
    "size",
    "weight",
    "productCategoryID",
    "productModelID",
    "sellStartDate",
    "sellEndDate",
    "discontinuedDate",
    "thumbNailPhoto",
    "thumbnailPhotoFileName",
    "productModel",
    "productCategory"
})
public class ProductType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "ProductNumber", required = true)
    protected String productNumber;
    @XmlElement(name = "Color", required = true, nillable = true)
    protected String color;
    @XmlElement(name = "StandardCost")
    protected double standardCost;
    @XmlElement(name = "ListPrice")
    protected double listPrice;
    @XmlElement(name = "Size", required = true, nillable = true)
    protected String size;
    @XmlElement(name = "Weight", required = true, type = Double.class, nillable = true)
    protected Double weight;
    @XmlElement(name = "ProductCategoryID", required = true, type = Integer.class, nillable = true)
    protected Integer productCategoryID;
    @XmlElement(name = "ProductModelID", required = true, type = Integer.class, nillable = true)
    protected Integer productModelID;
    @XmlElement(name = "SellStartDate", required = true)
    protected XMLGregorianCalendar sellStartDate;
    @XmlElement(name = "SellEndDate", required = true, nillable = true)
    protected XMLGregorianCalendar sellEndDate;
    @XmlElement(name = "DiscontinuedDate", required = true, nillable = true)
    protected XMLGregorianCalendar discontinuedDate;
    @XmlElement(name = "ThumbNailPhoto", required = true, nillable = true)
    protected byte[] thumbNailPhoto;
    @XmlElement(name = "ThumbnailPhotoFileName", required = true, nillable = true)
    protected String thumbnailPhotoFileName;
    @XmlElement(name = "ProductModel", required = true)
    protected ProductModelType productModel;
    @XmlElement(name = "ProductCategory", required = true)
    protected ProductCategoryType productCategory;
    @XmlAttribute(name = "ProductID", required = true)
    protected int productID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the productNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * Sets the value of the productNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductNumber(String value) {
        this.productNumber = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the standardCost property.
     * 
     */
    public double getStandardCost() {
        return standardCost;
    }

    /**
     * Sets the value of the standardCost property.
     * 
     */
    public void setStandardCost(double value) {
        this.standardCost = value;
    }

    /**
     * Gets the value of the listPrice property.
     * 
     */
    public double getListPrice() {
        return listPrice;
    }

    /**
     * Sets the value of the listPrice property.
     * 
     */
    public void setListPrice(double value) {
        this.listPrice = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWeight(Double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the productCategoryID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProductCategoryID() {
        return productCategoryID;
    }

    /**
     * Sets the value of the productCategoryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProductCategoryID(Integer value) {
        this.productCategoryID = value;
    }

    /**
     * Gets the value of the productModelID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProductModelID() {
        return productModelID;
    }

    /**
     * Sets the value of the productModelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProductModelID(Integer value) {
        this.productModelID = value;
    }

    /**
     * Gets the value of the sellStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSellStartDate() {
        return sellStartDate;
    }

    /**
     * Sets the value of the sellStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSellStartDate(XMLGregorianCalendar value) {
        this.sellStartDate = value;
    }

    /**
     * Gets the value of the sellEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSellEndDate() {
        return sellEndDate;
    }

    /**
     * Sets the value of the sellEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSellEndDate(XMLGregorianCalendar value) {
        this.sellEndDate = value;
    }

    /**
     * Gets the value of the discontinuedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDiscontinuedDate() {
        return discontinuedDate;
    }

    /**
     * Sets the value of the discontinuedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDiscontinuedDate(XMLGregorianCalendar value) {
        this.discontinuedDate = value;
    }

    /**
     * Gets the value of the thumbNailPhoto property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getThumbNailPhoto() {
        return thumbNailPhoto;
    }

    /**
     * Sets the value of the thumbNailPhoto property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setThumbNailPhoto(byte[] value) {
        this.thumbNailPhoto = ((byte[]) value);
    }

    /**
     * Gets the value of the thumbnailPhotoFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbnailPhotoFileName() {
        return thumbnailPhotoFileName;
    }

    /**
     * Sets the value of the thumbnailPhotoFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbnailPhotoFileName(String value) {
        this.thumbnailPhotoFileName = value;
    }

    /**
     * Gets the value of the productModel property.
     * 
     * @return
     *     possible object is
     *     {@link ProductModelType }
     *     
     */
    public ProductModelType getProductModel() {
        return productModel;
    }

    /**
     * Sets the value of the productModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductModelType }
     *     
     */
    public void setProductModel(ProductModelType value) {
        this.productModel = value;
    }

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCategoryType }
     *     
     */
    public ProductCategoryType getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCategoryType }
     *     
     */
    public void setProductCategory(ProductCategoryType value) {
        this.productCategory = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     */
    public int getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     */
    public void setProductID(int value) {
        this.productID = value;
    }

}
