//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.28 at 11:05:57 PM PDT 
//


package com.cmpe276.dbase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CatalogDescription" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element ref="{}ModelDescription"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ProductModelID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductModelType", propOrder = {
    "name",
    "catalogDescription",
    "modelDescription"
})
public class ProductModelType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "CatalogDescription", required = true, nillable = true)
    protected String catalogDescription;
    @XmlElement(name = "ModelDescription", required = true)
    protected ModelDescriptionType modelDescription;
    @XmlAttribute(name = "ProductModelID", required = true)
    protected int productModelID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the catalogDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogDescription() {
        return catalogDescription;
    }

    /**
     * Sets the value of the catalogDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogDescription(String value) {
        this.catalogDescription = value;
    }

    /**
     * Gets the value of the modelDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ModelDescriptionType }
     *     
     */
    public ModelDescriptionType getModelDescription() {
        return modelDescription;
    }

    /**
     * Sets the value of the modelDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelDescriptionType }
     *     
     */
    public void setModelDescription(ModelDescriptionType value) {
        this.modelDescription = value;
    }

    /**
     * Gets the value of the productModelID property.
     * 
     */
    public int getProductModelID() {
        return productModelID;
    }

    /**
     * Sets the value of the productModelID property.
     * 
     */
    public void setProductModelID(int value) {
        this.productModelID = value;
    }

}
