//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.28 at 11:05:57 PM PDT 
//


package com.cmpe276.dbase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SalesOrderDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesOrderDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderQty" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="UnitPriceDiscount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="LineTotal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element ref="{}Product"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SalesOrderDetailID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="SalesOrderID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesOrderDetailType", propOrder = {
    "orderQty",
    "productID",
    "unitPrice",
    "unitPriceDiscount",
    "lineTotal",
    "product"
})
public class SalesOrderDetailType {

    @XmlElement(name = "OrderQty")
    protected int orderQty;
    @XmlElement(name = "ProductID")
    protected int productID;
    @XmlElement(name = "UnitPrice")
    protected double unitPrice;
    @XmlElement(name = "UnitPriceDiscount")
    protected double unitPriceDiscount;
    @XmlElement(name = "LineTotal")
    protected double lineTotal;
    @XmlElement(name = "Product", required = true)
    protected ProductType product;
    @XmlAttribute(name = "SalesOrderDetailID", required = true)
    protected int salesOrderDetailID;
    @XmlAttribute(name = "SalesOrderID", required = true)
    protected int salesOrderID;

    /**
     * Gets the value of the orderQty property.
     * 
     */
    public int getOrderQty() {
        return orderQty;
    }

    /**
     * Sets the value of the orderQty property.
     * 
     */
    public void setOrderQty(int value) {
        this.orderQty = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     */
    public int getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     */
    public void setProductID(int value) {
        this.productID = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     */
    public double getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     */
    public void setUnitPrice(double value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the unitPriceDiscount property.
     * 
     */
    public double getUnitPriceDiscount() {
        return unitPriceDiscount;
    }

    /**
     * Sets the value of the unitPriceDiscount property.
     * 
     */
    public void setUnitPriceDiscount(double value) {
        this.unitPriceDiscount = value;
    }

    /**
     * Gets the value of the lineTotal property.
     * 
     */
    public double getLineTotal() {
        return lineTotal;
    }

    /**
     * Sets the value of the lineTotal property.
     * 
     */
    public void setLineTotal(double value) {
        this.lineTotal = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType }
     *     
     */
    public ProductType getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType }
     *     
     */
    public void setProduct(ProductType value) {
        this.product = value;
    }

    /**
     * Gets the value of the salesOrderDetailID property.
     * 
     */
    public int getSalesOrderDetailID() {
        return salesOrderDetailID;
    }

    /**
     * Sets the value of the salesOrderDetailID property.
     * 
     */
    public void setSalesOrderDetailID(int value) {
        this.salesOrderDetailID = value;
    }

    /**
     * Gets the value of the salesOrderID property.
     * 
     */
    public int getSalesOrderID() {
        return salesOrderID;
    }

    /**
     * Sets the value of the salesOrderID property.
     * 
     */
    public void setSalesOrderID(int value) {
        this.salesOrderID = value;
    }

}
