//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.28 at 11:05:57 PM PDT 
//


package com.cmpe276.dbase;

//import java.sql.Timestamp;
//import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SalesOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesOrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RevisionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ShipDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OnlineOrderFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="SalesOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PurchaseOrderNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AccountNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ShipToAddressID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="BillToAddressID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ShipMethod">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CreditCardApprovalCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SubTotal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TaxAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TotalDue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BillToAddress" type="{}AddressType"/>
 *         &lt;element name="ShipToAddress" type="{}AddressType"/>
 *         &lt;element ref="{}SalesOrderDetail"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SalesOrderID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesOrderType", propOrder = {
    "revisionNumber",
    "orderDate",
    "dueDate",
    "shipDate",
    "status",
    "onlineOrderFlag",
    "salesOrderNumber",
    "purchaseOrderNumber",
    "accountNumber",
    "customerID",
    "shipToAddressID",
    "billToAddressID",
    "shipMethod",
    "creditCardApprovalCode",
    "subTotal",
    "taxAmt",
    "freight",
    "totalDue",
    "comment",
    "billToAddress",
    "shipToAddress",
    "salesOrderDetail"
})
public class SalesOrderType {

    @XmlElement(name = "RevisionNumber")
    protected int revisionNumber;
    @XmlElement(name = "OrderDate", required = true)
    protected XMLGregorianCalendar orderDate;
    @XmlElement(name = "DueDate", required = true)
    protected XMLGregorianCalendar dueDate;
    @XmlElement(name = "ShipDate", required = true, nillable = true)
    protected XMLGregorianCalendar shipDate;
    @XmlElement(name = "Status")
    protected int status;
    @XmlElement(name = "OnlineOrderFlag")
    protected int onlineOrderFlag;
    @XmlElement(name = "SalesOrderNumber", required = true)
    protected String salesOrderNumber;
    @XmlElement(name = "PurchaseOrderNumber", required = true, nillable = true)
    protected String purchaseOrderNumber;
    @XmlElement(name = "AccountNumber", required = true, nillable = true)
    protected String accountNumber;
    @XmlElement(name = "CustomerID")
    protected int customerID;
    @XmlElement(name = "ShipToAddressID", required = true, type = Integer.class, nillable = true)
    protected Integer shipToAddressID;
    @XmlElement(name = "BillToAddressID", required = true, type = Integer.class, nillable = true)
    protected Integer billToAddressID;
    @XmlElement(name = "ShipMethod", required = true)
    protected String shipMethod;
    @XmlElement(name = "CreditCardApprovalCode", required = true, nillable = true)
    protected String creditCardApprovalCode;
    @XmlElement(name = "SubTotal")
    protected double subTotal;
    @XmlElement(name = "TaxAmt")
    protected double taxAmt;
    @XmlElement(name = "Freight")
    protected double freight;
    @XmlElement(name = "TotalDue")
    protected double totalDue;
    @XmlElement(name = "Comment", required = true, nillable = true)
    protected String comment;
    @XmlElement(name = "BillToAddress", required = true)
    protected AddressType billToAddress;
    @XmlElement(name = "ShipToAddress", required = true)
    protected AddressType shipToAddress;
    @XmlElement(name = "SalesOrderDetail", required = true)
    protected SalesOrderDetailType salesOrderDetail;
    @XmlAttribute(name = "SalesOrderID", required = true)
    protected String salesOrderID;

    /**
     * Gets the value of the revisionNumber property.
     * 
     */
    public int getRevisionNumber() {
        return revisionNumber;
    }

    /**
     * Sets the value of the revisionNumber property.
     * 
     */
    public void setRevisionNumber(int value) {
        this.revisionNumber = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderDate(XMLGregorianCalendar value) {
    	this.orderDate = value;
    	 
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the shipDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getShipDate() {
        return shipDate;
    }

    /**
     * Sets the value of the shipDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setShipDate(XMLGregorianCalendar value) {
        this.shipDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    /**
     * Gets the value of the onlineOrderFlag property.
     * 
     */
    public int isOnlineOrderFlag() {
        return onlineOrderFlag;
    }

    /**
     * Sets the value of the onlineOrderFlag property.
     * 
     */
    public void setOnlineOrderFlag(int value) {
        this.onlineOrderFlag = value;
    }

    /**
     * Gets the value of the salesOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesOrderNumber() {
        return salesOrderNumber;
    }

    /**
     * Sets the value of the salesOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesOrderNumber(String value) {
        this.salesOrderNumber = value;
    }

    /**
     * Gets the value of the purchaseOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseOrderNumber() {
        return purchaseOrderNumber;
    }

    /**
     * Sets the value of the purchaseOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseOrderNumber(String value) {
        this.purchaseOrderNumber = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     */
    public int getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     */
    public void setCustomerID(int value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the shipToAddressID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getShipToAddressID() {
        return shipToAddressID;
    }

    /**
     * Sets the value of the shipToAddressID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setShipToAddressID(Integer value) {
        this.shipToAddressID = value;
    }

    /**
     * Gets the value of the billToAddressID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBillToAddressID() {
        return billToAddressID;
    }

    /**
     * Sets the value of the billToAddressID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBillToAddressID(Integer value) {
        this.billToAddressID = value;
    }

    /**
     * Gets the value of the shipMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipMethod() {
        return shipMethod;
    }

    /**
     * Sets the value of the shipMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipMethod(String value) {
        this.shipMethod = value;
    }

    /**
     * Gets the value of the creditCardApprovalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditCardApprovalCode() {
        return creditCardApprovalCode;
    }

    /**
     * Sets the value of the creditCardApprovalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditCardApprovalCode(String value) {
        this.creditCardApprovalCode = value;
    }

    /**
     * Gets the value of the subTotal property.
     * 
     */
    public double getSubTotal() {
        return subTotal;
    }

    /**
     * Sets the value of the subTotal property.
     * 
     */
    public void setSubTotal(double value) {
        this.subTotal = value;
    }

    /**
     * Gets the value of the taxAmt property.
     * 
     */
    public double getTaxAmt() {
        return taxAmt;
    }

    /**
     * Sets the value of the taxAmt property.
     * 
     */
    public void setTaxAmt(double value) {
        this.taxAmt = value;
    }

    /**
     * Gets the value of the freight property.
     * 
     */
    public double getFreight() {
        return freight;
    }

    /**
     * Sets the value of the freight property.
     * 
     */
    public void setFreight(double value) {
        this.freight = value;
    }

    /**
     * Gets the value of the totalDue property.
     * 
     */
    public double getTotalDue() {
        return totalDue;
    }

    /**
     * Sets the value of the totalDue property.
     * 
     */
    public void setTotalDue(double value) {
        this.totalDue = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the billToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getBillToAddress() {
        return billToAddress;
    }

    /**
     * Sets the value of the billToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setBillToAddress(AddressType value) {
        this.billToAddress = value;
    }

    /**
     * Gets the value of the shipToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getShipToAddress() {
        return shipToAddress;
    }

    /**
     * Sets the value of the shipToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setShipToAddress(AddressType value) {
        this.shipToAddress = value;
    }

    /**
     * Gets the value of the salesOrderDetail property.
     * 
     * @return
     *     possible object is
     *     {@link SalesOrderDetailType }
     *     
     */
    public SalesOrderDetailType getSalesOrderDetail() {
        return salesOrderDetail;
    }

    /**
     * Sets the value of the salesOrderDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesOrderDetailType }
     *     
     */
    public void setSalesOrderDetail(SalesOrderDetailType value) {
        this.salesOrderDetail = value;
    }

    /**
     * Gets the value of the salesOrderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesOrderID() {
        return salesOrderID;
    }

    /**
     * Sets the value of the salesOrderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesOrderID(String value) {
        this.salesOrderID = value;
    }

}
